pipeline_name: "stock_predictor"

data_sourcing:
  ticker: "MSFT"

feature_engineering:
  target_col_transform: "log"

model_params:
  sequence_length: 60
  hidden_size: 50 # <-- Daha yetenekli varsayılan

training_params:
  epochs: 50 # <-- Daha uzun varsayılan eğitim
  lr: 0.001
  optimizer: "adam"
  test_size: 0.2
  validate_every: 5
  batch_size: 32 # <-- YENİ

system:
  caching_enabled: true
  cache_max_age_hours: 24