# app-stock-predictor/src/azuraforge_stockapp/config/stock_predictor_config.yml

pipeline_name: "stock_predictor"

data_sourcing:
  ticker: "MSFT"

model_params:
  sequence_length: 60
  hidden_size: 50

training_params:
  epochs: 50
  lr: 0.001
  optimizer: "adam"
  test_size: 0.2
  validate_every: 5 # Her 5 epoch'ta bir canlı tahmin grafiğini güncelle

# YENİ: Merkezi sistem ayarları artık burada değil, 
# .env ve docker-compose.yml'de yönetiliyor.
# Ancak eklenti seviyesinde caching'i açıp kapatmak için bu flag'i tutabiliriz.
system:
  caching_enabled: true
  cache_max_age_hours: 24