# app-stock-predictor/src/azuraforge_stockapp/config/stock_predictor_config.yml

pipeline_name: "stock_predictor"

data_sourcing:
  ticker: "MSFT"

# YENİ: Özellik mühendisliği ve dönüşüm ayarları
feature_engineering:
  target_col_transform: "log" # "log" veya "none" olabilir

model_params:
  sequence_length: 60
  hidden_size: 5

training_params:
  epochs: 50
  lr: 0.001
  optimizer: "adam"
  test_size: 0.2
  validate_every: 5

system:
  caching_enabled: true
  cache_max_age_hours: 24